### ISSUE TITLE
KeyError: Items

### ISSUE THREAD

**Issue by ItsCresent** [chorobikmichal/HQ-Trivia-BOT#7]
```
Traceback (most recent call last):
  File "trivia.py", line 287, in mouseReleaseEvent
    searchNow(alal)
  File "trivia.py", line 209, in searchNow
    ser(t,a1,a2,a3,question)
  File "trivia.py", line 121, in ser
    for item in results["items"]:
KeyError: 'items'
```
I literally cant even work out a fix to this

**Comment by U-r-Unknown** [comment]
Mail me onlimeuse321@gmail.com I will sort this issue

**Comment by FNGacemaverick** [comment]
I'm having the same issue. Has anyone here been able to solve it?

**Comment by MrBgoCH** [comment]
getting same issues - did it get resolved?

**Comment by Kayull** [comment]
[inputting image
*****************************************************************
When did the U.S. $2 bill leave circulation? Still in circulation 322312 1996
Traceback (most recent call last):
  File "trivia.py", line 285, in mouseReleaseEvent
    searchNow(alal)
  File "trivia.py", line 207, in searchNow
    ser(t,a1,a2,a3,question)
  File "trivia.py", line 119, in ser
    for item in results["items"]:
KeyError: 'items']

Used on a sample question. Anyone know a solution or is this dead?
